name: stream_feed_dart
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.1
  equatable: ^2.0.0
  dio: ^4.0.0
  jaguar_jwt: ^3.0.0

dev_dependencies:
  test: ^1.15.4
  build_runner: ^2.0.1
  json_serializable: ^4.1.1
  pedantic: ^1.9.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
